# scratch/data_seo_static.py
# SEO metadata & Static page contents (About, Privacy, Terms, Features, Contact) for all 12 languages

SEO_TITLES = {
    'index': {
        'it': 'Scaricare Video dai Social Network HD — All-in-One 1080p e 4K MP4 / MP3',
        'en': 'Social Media Video Downloader HD — All-in-One 1080p & 4K MP4 / MP3',
        'es': 'Descargador de Videos de Redes Sociales HD — Todo en Uno 1080p y 4K MP4 / MP3',
        'fr': 'Téléchargeur de Vidéos Réseaux Sociaux HD — Tout-en-Un 1080p et 4K MP4 / MP3',
        'de': 'Social Media Video Downloader HD — All-in-One 1080p & 4K MP4 / MP3',
        'hi': 'सोशल मीडिया वीडियो डाउनलोडर HD — ऑल-इन-वन 1080p और 4K MP4 / MP3',
        'ar': 'محمل فيديوهات وسائل التواصل الاجتماعي HD — الكل في واحد 1080p و 4K MP4 / MP3',
        'pt': 'Baixador de Vídeos de Redes Sociais HD — Tudo em Um 1080p e 4K MP4 / MP3',
        'bn': 'সোশ্যাল মিডিয়া ভিডিও ডাউনলোডার HD — অল-ইন-ওয়ান ১০৮০p ও ৪K MP4 / MP3',
        'ru': 'Загрузчик видео из соцсетей HD — Все в одном 1080p и 4K MP4 / MP3',
        'id': 'Pengunduh Video Media Sosial HD — Serba Guna 1080p & 4K MP4 / MP3',
        'zh': '全能社交媒体高清视频下载器 — 1080p 与 4K MP4 / MP3 无水印直链提取',
        'ur': 'سوشل میڈیا ویڈیو ڈاؤنلوڈر HD — آل ان ون 1080p اور 4K MP4 / MP3'
    },
    'facebook': {
        'it': 'Scaricare Video da Facebook HD — Salva Reel, Storie e Video FB Gratis',
        'en': 'Facebook Video Downloader HD — Save FB Reels, Stories & Watch Videos Free',
        'es': 'Descargador de Videos de Facebook HD — Descargar Reels, Stories y Videos FB Gratis',
        'fr': 'Téléchargeur de Vidéos Facebook HD — Enregistrez Reels, Stories et Vidéos FB',
        'de': 'Facebook Video Downloader HD — FB Reels, Storys & Videos kostenlos herunterladen',
        'hi': 'फेसबुक वीडियो डाउनलोडर HD — FB रील्स, स्टोरीज और वीडियो फ्री डाउनलोड करें',
        'ar': 'محمل فيديوهات فيسبوك HD — تنزيل ريلز وستوري وفيديوهات فيسبوك مجاناً',
        'pt': 'Baixador de Vídeos do Facebook HD — Salvar Reels, Stories e Vídeos do FB Grátis',
        'bn': 'ফেসবুক ভিডিও ডাউনলোডার HD — FB রিলস, স্টোরিজ ও ভিডিও ডাউনলোড করুন',
        'ru': 'Загрузчик видео Facebook HD — Скачать рилс, истории и видео FB бесплатно',
        'id': 'Pengunduh Video Facebook HD — Simpan FB Reels, Story & Video Gratis',
        'zh': 'Facebook 高清视频下载器 — 免费下载 FB Reels 短视频、快拍 Stories 与 Watch 视频',
        'ur': 'فیس بک ویڈیو ڈاؤنلوڈر HD — FB ریلز، اسٹوریز اور ویڈیوز مفت ڈاؤن لوڈ کریں'
    },
    'instagram': {
        'it': 'Scaricare Video da Instagram HD — Salva Reel, Storie, Foto e Carousel',
        'en': 'Instagram Video Downloader HD — Download Reels, Stories, Photos & Carousel',
        'es': 'Descargador de Instagram HD — Descargar Reels, Stories, Fotos y Carruseles',
        'fr': 'Téléchargeur Instagram HD — Télécharger Reels, Stories, Photos & Carrousels',
        'de': 'Instagram Video Downloader HD — Reels, Storys, Fotos & Karussell-Posts',
        'hi': 'इंस्टाग्राम वीडियो डाउनलोडर HD — रील्स, स्टोरीज, फोटोज और कैरोसेल डाउनलोड करें',
        'ar': 'محمل فيديوهات إنستغرام HD — تنزيل ريلز وستوري وصور وبوستات كاروسيل',
        'pt': 'Baixador do Instagram HD — Baixar Reels, Stories, Fotos e Carrossel Grátis',
        'bn': 'ইনস্টাগ্রাম ভিডিও ডাউনলোডার HD — রিলস, স্টোরিজ, ফটো ও ক্যারোসেল ডাউনলোড',
        'ru': 'Загрузчик Instagram HD — Скачать рилс, истории, фото и карусели бесплатно',
        'id': 'Pengunduh Instagram HD — Unduh Reels, Story, Foto & Postingan Korsel',
        'zh': 'Instagram 高清下载器 — 免登录下载 IG Reels 卷轴、快拍 Stories、照片与轮播图',
        'ur': 'انسٹاگرام ویڈیو ڈاؤنلوڈر HD — ریلز، اسٹوریز، تصاویر اور کیروسل ڈاؤن لوڈ کریں'
    },
    'tiktok': {
        'it': 'Scaricare Video TikTok Senza Watermark — Download Video e MP3 HD',
        'en': 'TikTok Downloader Without Watermark — Download TikTok Videos & MP3 HD',
        'es': 'Descargador de TikTok Sin Marca de Agua — Descargar Videos y MP3 HD',
        'fr': 'Téléchargeur TikTok Sans Filigrane — Télécharger Vidéos et MP3 TikTok HD',
        'de': 'TikTok Downloader Ohne Wasserzeichen — TikTok Videos & MP3 kostenlos herunterladen',
        'hi': 'टिकटॉक डाउनलोडर बिना वॉटरमार्क — टिकटॉक वीडियो और MP3 HD डाउनलोड करें',
        'ar': 'محمل تيك توك بدون علامة مائية — تنزيل مقاطع تيك توك وصوتيات MP3 عالية الدقة',
        'pt': 'Baixador do TikTok Sem Marca d’Água — Baixar Vídeos e MP3 do TikTok HD',
        'bn': 'টিকটক ডাউনলোডার ওয়াটারমার্ক ছাড়া — টিকটক ভিডিও ও MP3 HD ডাউনলোড করুন',
        'ru': 'Загрузчик TikTok без водяных знаков — Скачать видео и MP3 из ТикТок в HD',
        'id': 'Pengunduh TikTok Tanpa Watermark — Unduh Video TikTok & MP3 Kualitas HD',
        'zh': 'TikTok 无水印视频下载器 — 一键提取高清无水印短视频与热门 MP3 音乐伴奏',
        'ur': 'ٹک ٹاک ڈاؤنلوڈر بغیر واٹر مارک — ٹک ٹاک ویڈیوز اور MP3 HD ڈاؤن لوڈ کریں'
    },
    'youtube': {
        'it': 'Scaricare Video da YouTube HD — Download YouTube Shorts e MP3 320kbps',
        'en': 'YouTube Video Downloader & Shorts Converter — 1080p, 4K & MP3 Audio',
        'es': 'Descargador de YouTube y Conversor de Shorts — 1080p, 4K y Audio MP3',
        'fr': 'Téléchargeur YouTube & Convertisseur Shorts — 1080p, 4K & Audio MP3',
        'de': 'YouTube Video Downloader & Shorts Konverter — 1080p, 4K & MP3 Audio',
        'hi': 'यूट्यूब वीडियो डाउनलोडर और शॉर्ट्स कनवर्टर — 1080p, 4K और MP3 ऑडियो',
        'ar': 'محمل فيديوهات يوتيوب ومحول الشورتس — 1080p و 4K وصوتيات MP3 مجاناً',
        'pt': 'Baixador do YouTube e Conversor de Shorts — 1080p, 4K e Áudio MP3',
        'bn': 'ইউটিউব ভিডিও ডাউনলোডার ও শর্টস কনভার্টার — ১০৮০p, ৪K ও MP3 অডিও',
        'ru': 'Загрузчик видео с YouTube и Shorts — Скачать в 1080p, 4K и MP3 аудио',
        'id': 'Pengunduh Video YouTube & Konverter Shorts — 1080p, 4K & Audio MP3',
        'zh': 'YouTube 视频与 Shorts 短视频下载转换器 — 支持 1080p、4K 原画与 320kbps MP3',
        'ur': 'یوٹیوب ویڈیو ڈاؤنلوڈر اور شارٹس کنورٹر — 1080p، 4K اور MP3 آڈیو'
    },
    'snapchat': {
        'it': 'Scaricare Video da Snapchat HD — Salva Spotlight e Storie Pubbliche',
        'en': 'Snapchat Spotlight & Stories Downloader — Full 9:16 HD MP4 Free',
        'es': 'Descargador de Snapchat Spotlight y Stories — 9:16 Full HD MP4 Gratis',
        'fr': 'Téléchargeur Snapchat Spotlight et Stories — 9:16 Full HD MP4 Gratuit',
        'de': 'Snapchat Spotlight & Stories Downloader — Full 9:16 HD MP4 kostenlos',
        'hi': 'स्नैपचैट स्पॉटलाइट और स्टोरीज डाउनलोडर — 9:16 फुल एचडी MP4 फ्री',
        'ar': 'محمل سناب شات سبوت لايت وستوري — جودة 9:16 Full HD MP4 مجاناً',
        'pt': 'Baixador do Snapchat Spotlight e Stories — 9:16 Full HD MP4 Grátis',
        'bn': 'স্ন্যাপচ্যাট স্পটলাইট ও স্টোরিজ ডাউনলোডার — 9:16 ফুল HD MP4 ফ্রি',
        'ru': 'Загрузчик Snapchat Spotlight и историй — Видео 9:16 Full HD MP4 бесплатно',
        'id': 'Pengunduh Snapchat Spotlight & Story — Format 9:16 Full HD MP4 Gratis',
        'zh': 'Snapchat Spotlight 与快拍下载器 — 竖屏 9:16 全高清 MP4 永久无损保存',
        'ur': 'سنیپ چیٹ اسپاٹ لائٹ اور اسٹوریز ڈاؤنلوڈر — 9:16 فل ایچ ڈی MP4 مفت'
    },
    'threads': {
        'it': 'Scaricare Video da Threads HD — Salva Video, Foto e Audio da Meta Threads',
        'en': 'Threads Video Downloader — Save Meta Threads Videos, Audio & Photos HD',
        'es': 'Descargador de Threads — Descargar Videos, Audios y Fotos de Meta Threads HD',
        'fr': 'Téléchargeur de Vidéos Threads — Enregistrer Vidéos, Audios et Photos Threads HD',
        'de': 'Threads Video Downloader — Meta Threads Videos, Audio & Fotos in HD speichern',
        'hi': 'थ्रेड्स वीडियो डाउनलोडर — मेटा थ्रेड्स वीडियो, ऑडियो और तस्वीरें HD में डाउनलोड करें',
        'ar': 'محمل فيديوهات ثريدز — تنزيل مقاطع وصوتيات وصور ميتا ثريدز بجودة عالية',
        'pt': 'Baixador do Threads — Salvar Vídeos, Áudios e Fotos do Meta Threads HD',
        'bn': 'থ্রেডস ভিডিও ডাউনলোডার — মেটা থ্রেডস ভিডিও, অডিও ও ছবি HD ডাউনলোড করুন',
        'ru': 'Загрузчик видео Threads — Скачать видео, аудио и фото из Meta Threads в HD',
        'id': 'Pengunduh Video Threads — Simpan Video, Audio & Foto Meta Threads Kualitas HD',
        'zh': 'Threads 视频下载器 — 免费下载 Meta Threads 高清视频、语音备忘录与多图轮播',
        'ur': 'تھریڈز ویڈیو ڈاؤنلوڈر — میٹا تھریڈز ویڈیوز، آڈیو اور تصاویر HD میں محفوظ کریں'
    },
    'private': {
        'it': 'Downloader Video Privato — Salva Video Tramite Codice Sorgente',
        'en': 'Private Video Downloader — Extract Instagram, Facebook & TikTok Private Media',
        'es': 'Descargador de Videos Privados — Extraer Contenido Privado de Instagram y Facebook',
        'fr': 'Téléchargeur de Vidéos Privées — Extraire Médias Privés Instagram, FB & TikTok',
        'de': 'Privater Video Downloader — Private Videos von Instagram & Facebook herunterladen',
        'hi': 'प्राइवेट वीडियो डाउनलोडर — इंस्टाग्राम और फेसबुक की प्राइवेट मीडिया डाउनलोड करें',
        'ar': 'محمل الفيديوهات الخاصة — استخراج وسائط الحسابات الخاصة من إنستغرام وفيسبوك',
        'pt': 'Baixador de Vídeos Privados — Extrair Mídia Privada do Instagram e Facebook',
        'bn': 'প্রাইভেট ভিডিও ডাউনলোডার — ফেসবুক ও ইনস্টাগ্রাম প্রাইভেট মিডিয়া ডাউনলোড করুন',
        'ru': 'Загрузчик приватных видео — Скачать закрытые видео из Instagram и Facebook',
        'id': 'Pengunduh Video Privat — Ekstrak Media Privat Instagram, Facebook & TikTok',
        'zh': '私密视频下载器 — 基于安全页面源码解析提取 Instagram 与 Facebook 私密多媒体',
        'ur': 'پرائیویٹ ویڈیو ڈاؤنلوڈر — انسٹاگرام اور فیس بک کی پرائیویٹ میڈیا محفوظ کریں'
    },
    'about': {
        'it': 'Chi Siamo — downsocial.net Downloader Social Media Gratuito',
        'en': 'About Us — downsocial.net | Free All-in-One Social Video Downloader',
        'es': 'Sobre Nosotros — downsocial.net | Descargador Gratuito de Videos',
        'fr': 'À Propos de Nous — downsocial.net | Téléchargeur Vidéo Gratuit Tout-en-Un',
        'de': 'Über Uns — downsocial.net | Kostenloser All-in-One Video Downloader',
        'hi': 'हमारे बारे में — downsocial.net | मुफ्त ऑल-इन-वन सोशल वीडियो डाउनलोडर',
        'ar': 'من نحن — downsocial.net | محمل فيديوهات مجاني شامل لجميع المنصات',
        'pt': 'Sobre Nós — downsocial.net | Baixador de Vídeos Gratuito Tudo em Um',
        'bn': 'আমাদের সম্পর্কে — downsocial.net | ফ্রি অল-ইন-ওয়ান সোশ্যাল ভিডিও ডাউনলোডার',
        'ru': 'О сервисе — downsocial.net | Бесплатный универсальный загрузчик видео',
        'id': 'Tentang Kami — downsocial.net | Pengunduh Video Serba Guna Gratis',
        'zh': '关于我们 — downsocial.net | 免费全能社交媒体视频与音频提取平台',
        'ur': 'ہمارے بارے میں — downsocial.net | مفت آل ان ون سوشل ویڈیو ڈاؤنلوڈر'
    },
    'features': {
        'it': 'Funzionalità e Specifiche Tecniche — downsocial.net',
        'en': 'Platform Features & Capabilities — downsocial.net Video Suite',
        'es': 'Características y Capacidades de la Plataforma — downsocial.net',
        'fr': 'Fonctionnalités et Capacités — Suite Vidéo downsocial.net',
        'de': 'Funktionen & Spezifikationen — downsocial.net Video Suite',
        'hi': 'प्लेटफ़ॉर्म विशेषताएं और क्षमताएं — downsocial.net वीडियो सूट',
        'ar': 'مميزات وإمكانيات المنصة — باقة أدوات downsocial.net',
        'pt': 'Recursos e Capacidades da Plataforma — downsocial.net',
        'bn': 'প্ল্যাটফর্মের বৈশিষ্ট্য ও সুবিধাসমূহ — downsocial.net ভিডিও সুইট',
        'ru': 'Возможности и функции платформы — downsocial.net',
        'id': 'Fitur & Keunggulan Platform — downsocial.net Video Suite',
        'zh': '平台核心功能与技术特性 — downsocial.net 全能多媒体套件',
        'ur': 'پلیٹ فارم کی خصوصیات اور صلاحیتیں — downsocial.net ویڈیو سوٹ'
    },
    'contact': {
        'it': 'Contatti e Supporto Tecnico — downsocial.net',
        'en': 'Contact Support — downsocial.net 24/7 Global Help Desk',
        'es': 'Contacto y Soporte — Centro de Ayuda Global downsocial.net',
        'fr': 'Contact & Support — Centre d’Aide Global downsocial.net',
        'de': 'Kontakt & Support — downsocial.net 24/7 Hilfe-Center',
        'hi': 'संपर्क और सहायता — downsocial.net 24/7 सहायता केंद्र',
        'ar': 'اتصل بالدعم الفني — مركز المساعدة العالمي downsocial.net',
        'pt': 'Contato e Suporte — Central de Atendimento downsocial.net',
        'bn': 'যোগাযোগ ও সাপোর্ট — downsocial.net ২৪/৭ হেল্প ডেস্ক',
        'ru': 'Контакты и поддержка — Круглосуточная служба downsocial.net',
        'id': 'Hubungi Kami & Bantuan — Pusat Bantuan 24/7 downsocial.net',
        'zh': '联系我们与在线客服 — downsocial.net 24/7 全球技术支持中心',
        'ur': 'رابطہ اور سپورٹ — downsocial.net 24/7 گلوبل ہیلپ ڈیسک'
    },
    'privacy': {
        'it': 'Informativa sulla Privacy — downsocial.net',
        'en': 'Privacy Policy — downsocial.net Zero-Log & Data Protection Guarantee',
        'es': 'Política de Privacidad — Garantía de Cero Registros downsocial.net',
        'fr': 'Politique de Confidentialité — Garantie Sans Enregistrement downsocial.net',
        'de': 'Datenschutzerklärung — Zero-Log & Datenschutzgarantie downsocial.net',
        'hi': 'गोपनीयता नीति — downsocial.net ज़ीरो-लॉग और डेटा सुरक्षा गारंटी',
        'ar': 'سياسة الخصوصية — ضمان عدم تسجيل البيانات وحماية الخصوصية downsocial.net',
        'pt': 'Política de Privacidade — Garantia de Zero Registros downsocial.net',
        'bn': 'গোপনীয়তা নীতি — downsocial.net জিরো-লগ ও ডেটা সুরক্ষা নিশ্চয়তা',
        'ru': 'Политика конфиденциальности — Гарантия защиты данных downsocial.net',
        'id': 'Kebijakan Privasi — Jaminan Tanpa Log & Perlindungan Data downsocial.net',
        'zh': '隐私政策 — downsocial.net 零日志与高规格个人数据安全保护承诺',
        'ur': 'رازداری کی پالیسی — downsocial.net زیرو لاگ اور ڈیٹا تحفظ کی ضمانت'
    },
    'terms': {
        'it': 'Termini di Servizio — downsocial.net',
        'en': 'Terms of Service — downsocial.net Usage Guidelines & Fair Use Policy',
        'es': 'Términos de Servicio — Pautas de Uso y Política de Uso Justo',
        'fr': 'Conditions d’Utilisation — Règles d’Usage et Politique de Fair Use',
        'de': 'Nutzungsbedingungen — Nutzungsrichtlinien & Fair-Use-Richtlinie',
        'hi': 'सेवा की शर्तें — downsocial.net उपयोग दिशानिर्देश और उचित उपयोग नीति',
        'ar': 'شروط الخدمة — إرشادات الاستخدام وسياسة الاستخدام العادل downsocial.net',
        'pt': 'Termos de Serviço — Diretrizes de Uso e Política de Uso Justo',
        'bn': 'ব্যবহারের শর্তাবলী — downsocial.net নির্দেশিকা ও ফেয়ার ইউজ পলিসি',
        'ru': 'Условия использования — Правила сервиса и политика добросовестного использования',
        'id': 'Syarat Layanan — Panduan Penggunaan & Kebijakan Penggunaan Wajar',
        'zh': '服务条款 — downsocial.net 使用守则、版权合规声明与合理使用政策',
        'ur': 'شرائط و ضوابط — downsocial.net استعمال کے رہنما اصول اور منصفانہ استعمال کی پالیسی'
    }
}

SEO_DESCS = {
    'index': {
        'it': 'Scarica video, reel, shorts e storie da YouTube, TikTok, Instagram, Facebook, Snapchat e Threads in 1080p HD, 4K e audio MP3 senza watermark.',
        'it': 'Scaricare Video dai Social Network HD — All-in-One 1080p e 4K MP4 / MP3',
        'en': 'Download videos, reels, shorts & stories from Facebook, Instagram, TikTok, YouTube, Snapchat and Threads in original 1080p, 4K & MP3 audio without watermarks or login.',
        'es': 'Descarga videos, reels, shorts y stories de Facebook, Instagram, TikTok, YouTube, Snapchat y Threads en 1080p original, 4K y audio MP3 sin marcas de agua ni registro.',
        'fr': 'Téléchargez vidéos, reels, shorts et stories depuis Facebook, Instagram, TikTok, YouTube, Snapchat et Threads en 1080p original, 4K et MP3 sans filigrane ni inscription.',
        'de': 'Laden Sie Videos, Reels, Shorts und Storys von Facebook, Instagram, TikTok, YouTube, Snapchat und Threads in 1080p, 4K und MP3 ohne Wasserzeichen oder Anmeldung herunter.',
        'hi': 'फेसबुक, इंस्टाग्राम, टिकटॉक, यूट्यूब, स्नैपचैट और थ्रेड्स से मूल 1080p, 4K और MP3 में बिना वॉटरमार्क और बिना लॉगिन के वीडियो, रील्स और शॉर्ट्स डाउनलोड करें।',
        'ar': 'قم بتنزيل الفيديوهات والريلز والقصص من فيسبوك وإنستغرام وتيك توك ويوتيوب وسناب شات وثريدز بجودة 1080p و 4K وصوت MP3 مجاناً وبدون علامة مائية.',
        'pt': 'Baixe vídeos, reels, shorts e stories do Facebook, Instagram, TikTok, YouTube, Snapchat e Threads em 1080p original, 4K e MP3 sem marcas d’água ou login.',
        'bn': 'ফেসবুক, ইনস্টাগ্রাম, টিকটক, ইউটিউব, স্ন্যাপচ্যাট ও থ্রেডস থেকে ওয়াটারমার্ক ছাড়াই আসল ১০৮০p, ৪K এবং MP3 অডিওতে ভিডিও ও রিলস ডাউনলোড করুন।',
        'ru': 'Скачивайте видео, рилс, шортс и истории с Facebook, Instagram, TikTok, YouTube, Snapchat и Threads в 1080p, 4K и MP3 без водяных знаков и регистрации.',
        'id': 'Unduh video, reels, shorts & cerita dari Facebook, Instagram, TikTok, YouTube, Snapchat, dan Threads dalam resolusi 1080p, 4K & audio MP3 tanpa watermark.',
        'zh': '全面支持解析下载 Facebook、Instagram、TikTok、YouTube、Snapchat 与 Threads 的高清视频、Reels 短剧、Stories 快拍与 320kbps MP3 音乐，免注册且无水印。',
        'ur': 'فیس بک، انسٹاگرام، ٹک ٹاک، یوٹیوب، سنیپ چیٹ اور تھریڈز سے اصل 1080p، 4K اور MP3 میں بغیر کسی واٹر مارک اور لاگ ان کے ویڈیوز ڈاؤن لوڈ کریں۔'
    },
    'facebook': {
        'it': 'Scarica video, Facebook Reels, storie e video Watch in 1080p Full HD e audio MP3. Veloce, sicuro, senza pubblicità né login.',
        'it': 'Scaricare Video da Facebook HD — Salva Reel, Storie e Video FB Gratis',
        'en': 'Fast Facebook video downloader. Download FB Reels, Watch videos, Stories and private groups in 1080p Full HD MP4 and 320kbps MP3 audio free.',
        'es': 'Descargador rápido de Facebook. Descarga FB Reels, videos de Watch, Stories y grupos en 1080p Full HD MP4 y audio MP3 a 320kbps gratis.',
        'fr': 'Téléchargeur vidéo Facebook rapide. Téléchargez Reels FB, vidéos Watch, Stories et groupes en 1080p Full HD MP4 et audio MP3 320 kbps.',
        'de': 'Schneller Facebook Video Downloader. Laden Sie FB Reels, Watch-Videos, Storys und Gruppen in 1080p Full HD MP4 und 320kbps MP3 kostenlos herunter.',
        'hi': 'तेज़ फेसबुक वीडियो डाउनलोडर। FB रील्स, वॉच वीडियो, स्टोरीज और ग्रुप वीडियो 1080p फुल एचडी MP4 और 320kbps MP3 में फ्री डाउनलोड करें।',
        'ar': 'محمل فيديوهات فيسبوك فائق السرعة. قم بتنزيل ريلز وفيديوهات وستوري ومجموعات فيسبوك بدقة 1080p MP4 وصوت MP3 عالي النقاء مجاناً.',
        'pt': 'Baixador rápido do Facebook. Baixe FB Reels, vídeos Watch, Stories e grupos em 1080p Full HD MP4 e áudio MP3 de 320kbps gratuitamente.',
        'bn': 'দ্রুতগতির ফেসবুক ভিডিও ডাউনলোডার। FB রিলস, ওয়াচ ভিডিও ও স্টোরিজ ১০৮০p ফুল HD MP4 ও ৩২০kbps MP3 অডিওতে সম্পূর্ণ ফ্রিতে ডাউনলোড করুন।',
        'ru': 'Быстрый загрузчик видео с Facebook. Скачивайте рилс, видео Watch и истории в 1080p Full HD MP4 и MP3 аудио 320 кбит/с бесплатно.',
        'id': 'Pengunduh video Facebook kilat. Unduh FB Reels, video Watch, Story, dan grup publik dalam format 1080p Full HD MP4 dan audio MP3 320kbps gratis.',
        'zh': '超高速 Facebook 视频下载利器。支持 1080p 全高清 MP4 与 320kbps MP3 解析，轻松下载 FB Reels 短视频、Stories 快拍与 Watch 长视频。',
        'ur': 'تیز ترین فیس بک ویڈیو ڈاؤنلوڈر۔ FB ریلز، واچ ویڈیوز اور اسٹوریز کو 1080p فل ایچ ڈی MP4 اور 320kbps MP3 آڈیو میں مفت ڈاؤن لوڈ کریں۔'
    },
    'instagram': {
        'it': 'Scarica Instagram Reels, Storie, Foto e post Carousel in risoluzione originale HD. Nessun watermark, 100% gratuito e anonimo.',
        'it': 'Scaricare Video da Instagram HD — Salva Reel, Storie, Foto e Carousel',
        'en': 'Download Instagram Reels, Stories, Photos & Carousel posts in original resolution without watermark. Fast, safe, and no login required.',
        'es': 'Descarga Reels, Stories, Fotos y Carruseles de Instagram en resolución original sin marca de agua. Rápido, seguro y sin iniciar sesión.',
        'fr': 'Téléchargez Reels, Stories, Photos et Carrousels Instagram en résolution originale sans filigrane. Rapide, sécurisé et sans connexion.',
        'de': 'Laden Sie Instagram Reels, Storys, Fotos und Karussell-Beiträge in Originalauflösung ohne Wasserzeichen herunter. Sicher und ohne Login.',
        'hi': 'इंस्टाग्राम रील्स, स्टोरीज, फोटो और कैरोसेल बिना वॉटरमार्क के मूल रिज़ॉल्यूशन में डाउनलोड करें। सुरक्षित और बिना लॉगिन के।',
        'ar': 'قم بتنزيل ريلز وقصص وصور إنستغرام والبوستات متعددة الصور بأعلى دقة أصلية بدون علامات مائية وبدون الحاجة لتسجيل الدخول.',
        'pt': 'Baixe Reels, Stories, Fotos e Carrosséis do Instagram na resolução original e sem marca d’água. Rápido, seguro e sem login.',
        'bn': 'ইনস্টাগ্রাম রিলস, স্টোরিজ, ফটো ও ক্যারোসেল আসল রেজোলিউশনে ওয়াটারমার্ক ছাড়া ডাউনলোড করুন। নিরাপদ ও লগইন ছাড়াই কার্যকর।',
        'ru': 'Скачивайте рилс, истории, фото и карусели из Instagram в оригинальном разрешении без водяных знаков и без входа в аккаунт.',
        'id': 'Unduh Instagram Reels, Story, Foto, dan postingan Korsel dalam resolusi asli tanpa watermark. Cepat, aman, dan tanpa perlu login.',
        'zh': '无需登录账号，即可将 Instagram Reels 卷轴、24小时快拍 Stories、高清原图与多图轮播相册提取下载至手机与电脑。',
        'ur': 'انسٹاگرام ریلز، اسٹوریز، تصاویر اور کیروسل کو بغیر کسی واٹر مارک کے اصل ریزولوشن میں ڈاؤن لوڈ کریں۔ تیز، محفوظ اور بغیر لاگ ان۔'
    },
    'tiktok': {
        'it': "Scarica video TikTok senza watermark in HD MP4 ed estrai l'audio MP3 a 320kbps. Veloce, gratuito e senza installare app.",
        'it': 'Scaricare Video TikTok Senza Watermark — Download Video e MP3 HD',
        'en': 'Download TikTok videos without watermark in HD MP4. Extract original TikTok viral audio and background music as 320kbps MP3.',
        'es': 'Descarga videos de TikTok sin marca de agua en HD MP4. Extrae audios virales y música de fondo en MP3 a 320kbps.',
        'fr': 'Téléchargez vidéos TikTok sans filigrane en HD MP4. Extrayez l’audio viral et la musique en MP3 haute qualité 320 kbps.',
        'de': 'Laden Sie TikTok-Videos ohne Wasserzeichen in HD MP4 herunter. Extrahieren Sie Original-Soundtracks und Musik als 320kbps MP3.',
        'hi': 'टिकटॉक वीडियो बिना वॉटरमार्क के HD MP4 में डाउनलोड करें। बैकग्राउंड म्यूजिक और वायरल ऑडियो को 320kbps MP3 में निकालें।',
        'ar': 'قم بتنزيل مقاطع تيك توك بدون العلامة المائية المزعجة بدقة HD MP4، مع إمكانية استخراج الصوت والموسيقى بصيغة MP3 نقية.',
        'pt': 'Baixe vídeos do TikTok sem marca d’água em HD MP4. Extraia músicas virais e áudios originais diretamente em MP3 de 320kbps.',
        'bn': 'কোনো ওয়াটারমার্ক ছাড়া টিকটক ভিডিও HD MP4-এ ডাউনলোড করুন। আসল ব্যাকগ্রাউন্ড মিউজিক ৩২০kbps MP3 ফরম্যাটে সেভ করুন।',
        'ru': 'Скачивайте видео из TikTok без водяного знака в HD MP4. Извлекайте оригинальные треки и вирусные звуки в формате MP3 320 кбит/с.',
        'id': 'Unduh video TikTok tanpa tanda air dalam kualitas HD MP4. Ekstrak musik viral dan trek audio asli langsung ke format MP3 320kbps.',
        'zh': '全自动去除 TikTok 弹跳水印，直接下载原始 1080p 60FPS 超清视频源文件，并可独立提取 320kbps 伴奏音频 MP3。',
        'ur': 'بغیر واٹر مارک کے ٹک ٹاک ویڈیوز HD MP4 میں ڈاؤن لوڈ کریں۔ وائرل ساؤنڈ اور میوزک کو 320kbps MP3 میں محفوظ کریں۔'
    },
    'youtube': {
        'it': 'Scarica video e Shorts da YouTube in 1080p, 2K, 4K UHD ed estrai tracce audio MP3 a 320kbps. Nessuna pubblicità, 100% gratuito.',
        'it': 'Scaricare Video da YouTube HD — Download YouTube Shorts e MP3 320kbps',
        'en': 'Ultra-fast YouTube video downloader & Shorts converter. Download 1080p, 2K, 4K UHD MP4 videos and studio-grade 320kbps MP3 audio.',
        'es': 'Descargador ultrarrápido de YouTube y conversor de Shorts. Descarga videos en 1080p, 2K, 4K UHD MP4 y audio MP3 a 320kbps.',
        'fr': 'Téléchargeur YouTube ultra-rapide et convertisseur Shorts. Téléchargez des vidéos 1080p, 2K, 4K UHD MP4 et audio MP3 320 kbps.',
        'de': 'Ultraschneller YouTube Downloader & Shorts Konverter. Laden Sie 1080p, 2K, 4K UHD Videos und 320kbps MP3-Audio herunter.',
        'hi': 'अल्ट्रा-फास्ट यूट्यूब वीडियो डाउनलोडर और शॉर्ट्स कनवर्टर। 1080p, 2K, 4K UHD वीडियो और 320kbps MP3 ऑडियो फ्री डाउनलोड करें।',
        'ar': 'أسرع محمل لفيديوهات يوتيوب ومقاطع Shorts. تحميل بدقة 1080p و 2K و 4K Ultra HD وصوتيات MP3 عالية الوضوح مجاناً وبدون قيود.',
        'pt': 'Baixador ultrarrápido do YouTube e conversor de Shorts. Baixe vídeos em 1080p, 2K, 4K UHD MP4 e áudio MP3 de estúdio a 320kbps.',
        'bn': 'সুপার-ফাস্ট ইউটিউব ভিডিও ও শর্টস ডাউনলোডার। ১০৮০p, ২K, ৪K আল্ট্রা HD MP4 ভিডিও এবং ৩২০kbps MP3 অডিও ডাউনলোড করুন।',
        'ru': 'Сверхбыстрый загрузчик видео с YouTube и Shorts. Скачивайте в 1080p, 2K, 4K UHD MP4 и конвертируйте в студийный MP3 320 кбит/с.',
        'id': 'Pengunduh video YouTube super cepat & konverter Shorts. Unduh video 1080p, 2K, 4K UHD MP4 dan audio MP3 studio 320kbps gratis.',
        'zh': '支持解析 YouTube 长视频与 Shorts 短片，支持 1080p、2K、4K 超高清画质音画合流，并提供毫秒级转换 320kbps MP3。',
        'ur': 'انتہائی تیز رفتار یوٹیوب ویڈیو ڈاؤنلوڈر اور شارٹس کنورٹر۔ 1080p، 2K، 4K UHD ویڈیوز اور 320kbps MP3 آڈیو مفت ڈاؤن لوڈ کریں۔'
    },
    'snapchat': {
        'it': 'Salva video Spotlight e storie pubbliche di Snapchat in qualità 1080p HD prima della loro scadenza. Nessuna registrazione necessaria.',
        'it': 'Scaricare Video da Snapchat HD — Salva Spotlight e Storie Pubbliche',
        'en': 'Download Snapchat Spotlight clips & public Stories in full 9:16 vertical HD MP4 before they expire. 100% anonymous without notifications.',
        'es': 'Descarga clips de Snapchat Spotlight y Stories públicas en vertical 9:16 Full HD antes de que caduquen. Anónimo y sin notificaciones.',
        'fr': 'Téléchargez des clips Snapchat Spotlight et Stories publiques en 9:16 vertical Full HD avant expiration. 100% anonyme sans alertes.',
        'de': 'Laden Sie Snapchat Spotlight-Videos & Storys in vertikalem 9:16 Full HD MP4 herunter, bevor sie ablaufen. Ohne Screenshots oder Benachrichtigungen.',
        'hi': 'स्नैपचैट स्पॉटलाइट और पब्लिक स्टोरीज को 24 घंटे में समाप्त होने से पहले 9:16 फुल एचडी MP4 में डाउनलोड करें। पूरी तरह से गोपनीय।',
        'ar': 'احفظ مقاطع سناب شات سبوت لايت والقصص العامة بدقة 9:16 Full HD قبل انتهاء صلاحيتها خلال 24 ساعة. تنزيل مجهول تماماً وبدون إشعارات.',
        'pt': 'Baixe clipes do Snapchat Spotlight e Stories públicos em 9:16 vertical Full HD antes de expirarem. Totalmente anônimo e sem avisos.',
        'bn': '২৪ ঘণ্টার সময়সীমা শেষ হওয়ার আগেই স্ন্যাপচ্যাট স্পটলাইট ও পাবলিক স্টোরিজ ৯:১৬ ভার্টিক্যাল Full HD MP4 ফরম্যাটে সেভ করুন। সম্পূর্ণ গোপনীয়।',
        'ru': 'Скачивайте ролики Snapchat Spotlight и публичные истории в вертикальном 9:16 Full HD MP4 до их исчезновения. Полная анонимность.',
        'id': 'Unduh klip Snapchat Spotlight dan Story publik dalam format vertikal 9:16 Full HD MP4 sebelum kedaluwarsa. 100% anonim tanpa notifikasi.',
        'zh': '在24小时失效前，将 Snapchat Spotlight 竖屏短片与公开 Stories 保存为无水印 9:16 全高清 MP4，全程匿名不触发截图提醒。',
        'ur': 'سنیپ چیٹ اسپاٹ لائٹ اور پبلک اسٹوریز کو ختم ہونے سے پہلے 9:16 ورٹیکل فل ایچ ڈی MP4 میں ڈاؤن لوڈ کریں۔ بغیر کسی نوٹیفکیشن کے مکمل پرائیویٹ۔'
    },
    'threads': {
        'it': 'Scarica video, album fotografici e note vocali da Meta Threads in 1080p Full HD e MP3. Strumento online rapido e senza limiti.',
        'it': 'Scaricare Video da Threads HD — Salva Video, Foto e Audio da Meta Threads',
        'en': 'Download Meta Threads videos, voice notes, carousel photos & MP3 audio in original 1080p Full HD without extra compression or login.',
        'es': 'Descarga videos, notas de voz, fotos de carrusel y audios de Meta Threads en 1080p Full HD sin compresión extra ni login.',
        'fr': 'Téléchargez vidéos, notes vocales, carrousels et audios Meta Threads en 1080p Full HD d’origine sans compression ni connexion.',
        'de': 'Laden Sie Meta Threads Videos, Sprachnachrichten, Karussell-Fotos und MP3 in originalem 1080p Full HD ohne Login herunter.',
        'hi': 'मेटा थ्रेड्स वीडियो, वॉयस नोट्स, कैरोसेल फोटो और ऑडियो मूल 1080p फुल एचडी में बिना किसी अतिरिक्त संपीड़न या लॉगिन के डाउनलोड करें।',
        'ar': 'قم بتنزيل مقاطع الفيديو والتسجيلات الصوتية والصور المتعددة من منصة ميتا ثريدز بجودة 1080p Full HD نقية وبدون الحاجة لتسجيل الدخول.',
        'pt': 'Baixe vídeos do Meta Threads, notas de voz, fotos de carrossel e áudios em 1080p Full HD original sem compressão extra ou login.',
        'bn': 'মেটা থ্রেডস ভিডিও, ভয়েস নোট, ক্যারোসেল ছবি এবং অডিও কোনো অতিরিক্ত কম্প্রেশন বা লগইন ছাড়াই আসল ১০৮০p ফুল HD কোয়ালিটিতে ডাউনলোড করুন।',
        'ru': 'Скачивайте видео, голосовые заметки, фото-карусели и аудио из Meta Threads в оригинальном качестве 1080p Full HD без сжатия.',
        'id': 'Unduh video Meta Threads, rekaman suara, foto korsel, dan audio dalam 1080p Full HD asli tanpa kompresi tambahan atau login.',
        'zh': '专为 Meta Threads 打造的专业提取工具。无损下载 1080p 全高清视频短片、语音备忘录 MP3 及多图轮播相册，无需关联账号。',
        'ur': 'میٹا تھریڈز ویڈیوز، وائس نوٹس، کیروسل تصاویر اور آڈیو کو بغیر کسی اضافی کمپریشن یا لاگ ان کے اصل 1080p فل ایچ ڈی میں ڈاؤن لوڈ کریں۔'
    },
    'private': {
        'it': 'Estrai e scarica video con restrizioni di privacy incollando il codice sorgente della pagina in modo sicuro sul tuo browser.',
        'it': 'Downloader Video Privato — Salva Video Tramite Codice Sorgente',
        'en': 'Secure private video downloader. Extract private Instagram reels, Facebook closed group videos, and restricted posts safely via source code.',
        'es': 'Descargador seguro de videos privados. Extrae reels privados de Instagram y videos de grupos de Facebook mediante código fuente.',
        'fr': 'Téléchargeur sécurisé de vidéos privées. Extrayez les reels Instagram privés et vidéos de groupes Facebook via le code source.',
        'de': 'Sicherer privater Video Downloader. Extrahieren Sie private Instagram Reels und geschützte Facebook Videos sicher via Quellcode.',
        'hi': 'सुरक्षित प्राइवेट वीडियो डाउनलोडर। इंस्टाग्राम रील्स और फेसबुक प्राइवेट ग्रुप्स के वीडियो सुरक्षित रूप से सोर्स कोड द्वारा निकालें।',
        'ar': 'محمل الفيديوهات الخاصة الآمن. استخرج ريلز إنستغرام الخاصة وفيديوهات مجموعات فيسبوك المغلقة بأمان تام عبر كود المصدر.',
        'pt': 'Baixador seguro de vídeos privados. Extraia reels privados do Instagram e vídeos de grupos fechados do Facebook via código-fonte.',
        'bn': 'নিরাপদ প্রাইভেট ভিডিও ডাউনলোডার। পেইজ সোর্স কোডের মাধ্যমে ইনস্টাগ্রাম ও ফেসবুকের প্রাইভেট মিডিয়া নিরাপদে এক্সট্র্যাক্ট করুন।',
        'ru': 'Безопасный загрузчик приватных видео. Скачивайте закрытые рилс из Instagram и закрытых групп Facebook через исходный код страницы.',
        'id': 'Pengunduh video privat yang aman. Ekstrak reels privat Instagram dan video grup tertutup Facebook secara aman via kode sumber halaman.',
        'zh': '安全可靠的私密多媒体提取方案。依托前端安全网页源代码解析技术，轻松下载有权限查看的 Instagram 与 Facebook 私密视频。',
        'ur': 'محفوظ پرائیویٹ ویڈیو ڈاؤنلوڈر۔ انسٹاگرام کی پرائیویٹ ریلز اور فیس بک کے بند گروپس کی ویڈیوز پیج سورس کوڈ کے ذریعے محفوظ کریں۔'
    },
    'about': {
        'it': 'Scopri di più sulla nostra missione per offrire il downloader video e audio più veloce, sicuro e privo di annunci sul web.',
        'it': 'Chi Siamo — downsocial.net Downloader Social Media Gratuito',
        'en': 'Learn about downsocial.net: our core philosophy, zero-data collection architecture, and high-performance social video extraction mission.',
        'es': 'Conoce downsocial.net: nuestra filosofía, arquitectura de cero recolección de datos y misión de descargas rápidas y seguras.',
        'fr': 'Découvrez downsocial.net : notre philosophie, architecture sans collecte de données et mission d’extraction vidéo haute performance.',
        'de': 'Erfahren Sie mehr über downsocial.net: Unsere Mission, Zero-Data-Architektur und hochperformante Video-Extraktion.',
        'hi': 'downsocial.net के बारे में जानें: हमारा मिशन, ज़ीरो-डेटा संग्रह आर्किटेक्चर और उच्च प्रदर्शन सोशल वीडियो डाउनलोडिंग।',
        'ar': 'تعرف على downsocial.net: فلسفتنا القائمة على الخصوصية، وبنيتنا التحتية الخالية من تسجيل البيانات، ومهمتنا في تسهيل تحميل الوسائط.',
        'pt': 'Saiba mais sobre o downsocial.net: nossa missão, arquitetura sem coleta de dados e downloads de alta performance.',
        'bn': 'downsocial.net সম্পর্কে জানুন: আমাদের মূল দর্শন, জিরো-ডেটা কালেকশন প্রযুক্তি এবং দ্রুততম মিডিয়া এক্সট্র্যাকশন সেবা।',
        'ru': 'Узнайте больше о downsocial.net: наша миссия, архитектура без сбора данных и высокоскоростная загрузка видео из соцсетей.',
        'id': 'Pelajari tentang downsocial.net: filosofi kami, arsitektur tanpa pengumpulan data pribadi, dan misi pengunduhan video tercepat.',
        'zh': '了解 downsocial.net 平台创立愿景：坚持零用户数据追踪架构、提供纯净免费的高速全能多媒体下载服务。',
        'ur': 'downsocial.net کے بارے میں جانیں: ہماری رازداری کی پالیسی، زیرو ڈیٹا کلیکشن انفراسٹرکچر اور تیز ترین ویڈیو ڈاؤن لوڈنگ مشن۔'
    },
    'features': {
        'it': 'Esplora le caratteristiche tecniche, il supporto dei codec e le capacità di estrazione video 4K e MP3 a 320kbps di downsocial.',
        'it': 'Funzionalità e Specifiche Tecniche — downsocial.net',
        'en': 'Explore all technical features of downsocial: 1080p/4K MP4 stream extraction, real-time 320kbps MP3 transcoding, and zero-watermark engine.',
        'es': 'Explora las características técnicas de downsocial: extracción 1080p/4K, transcodificación MP3 a 320kbps y motor sin marcas de agua.',
        'fr': 'Explorez les caractéristiques techniques de downsocial : extraction 1080p/4K, transcodage MP3 320 kbps et moteur sans filigrane.',
        'de': 'Entdecken Sie alle technischen Features: 1080p/4K Videoextraktion, Echtzeit-320kbps MP3-Transcodierung und Wasserzeichen-Entfernung.',
        'hi': 'downsocial की सभी तकनीकी विशेषताएं देखें: 1080p/4K MP4 एक्सट्रैक्शन, रीयल-टाइम 320kbps MP3 कनवर्टर और बिना वॉटरमार्क इंजन।',
        'ar': 'اكتشف جميع الإمكانيات التقنية لمنصة downsocial: استخراج 1080p/4K، تحويل صوتي فوري إلى 320kbps MP3، ومحرك خالٍ من العلامات المائية.',
        'pt': 'Explore todos os recursos técnicos do downsocial: extração em 1080p/4K, transcodificação para MP3 a 320kbps e sem marcas d’água.',
        'bn': 'downsocial-এর কারিগরি বৈশিষ্ট্যসমূহ দেখুন: ১০৮০p/৪K MP4 এক্সট্র্যাকশন, রিয়েল-টাইম ৩২০kbps MP3 অডিও কনভার্সন ও ওয়াটারমার্কহীন ইঞ্জিন।',
        'ru': 'Изучите технические возможности downsocial: захват потоков 1080p/4K, транскодирование в MP3 320 кбит/с и удаление водяных знаков.',
        'id': 'Jelajahi fitur teknis downsocial: ekstraksi 1080p/4K MP4, konversi audio real-time MP3 320kbps, dan engine bebas watermark.',
        'zh': '全面解析 downsocial 核心技术优势：毫秒级 1080p/4K 原画流媒体提取、实时 320kbps 高保真 MP3 音频转码与全自动去水印引擎。',
        'ur': 'downsocial کی تمام تکنیکی خصوصیات دیکھیں: 1080p/4K MP4 اسٹریمنگ، رئیل ٹائم 320kbps MP3 ٹرانسکوڈنگ اور واٹر مارک لیس انجن۔'
    },
    'contact': {
        'it': 'Contatta il nostro team di assistenza clienti 24/7 per segnalare link non funzionanti o richiedere informazioni.',
        'it': 'Contatti e Supporto Tecnico — downsocial.net',
        'en': 'Contact the downsocial support team for broken URL reports, platform bug fixes, API partnerships, and user support. 24-hour response SLA.',
        'es': 'Contacta al soporte de downsocial para reportar enlaces caídos, errores de plataforma o alianzas. Respuesta garantizada en 24 horas.',
        'fr': 'Contactez l’équipe d’assistance downsocial pour signaler un lien défectueux ou poser vos questions. Réponse garantie sous 24h.',
        'de': 'Kontaktieren Sie das downsocial Support-Team bei fehlerhaften Links, Fehlern oder Partnerschaftsanfragen. Antwort innerhalb von 24h.',
        'hi': 'टूटे हुए वीडियो लिंक, बग रिपोर्ट या सहायता के लिए downsocial सपोर्ट टीम से संपर्क करें। 24 घंटे में समाधान की गारंटी।',
        'ar': 'تواصل مع فريق دعم downsocial للإبلاغ عن الروابط المتعطلة أو الأخطاء التقنية. نضمن الرد خلال 24 ساعة كحد أقصى.',
        'pt': 'Entre em contato com a equipe de suporte do downsocial para relatar links com problemas ou dúvidas. Resposta em até 24 horas.',
        'bn': 'যেকোনো সমস্যা, নষ্ট লিংক রিপোর্ট বা সাধারণ সহায়তার জন্য downsocial সাপোর্ট টিমের সাথে যোগাযোগ করুন। ২৪ ঘণ্টার মধ্যে প্রতিকার।',
        'ru': 'Свяжитесь со службой поддержки downsocial для сообщения о неработающих ссылках или ошибках. Ответ в течение 24 часов.',
        'id': 'Hubungi tim bantuan downsocial untuk pelaporan tautan rusak atau bantuan teknis. Kami merespon dalam waktu maksimal 24 jam.',
        'zh': '遇到失效链接或解析异常？随时联系 downsocial 全球技术支持客服。我们承诺在 24 小时内为您排查解决。',
        'ur': 'خراب لنکس کی رپورٹنگ، تکنیکی سوالات یا مدد کے لیے downsocial سپورٹ ٹیم سے رابطہ کریں۔ 24 گھنٹوں کے اندر جواب کی ضمانت۔'
    },
    'privacy': {
        'it': 'Leggi la nostra politica a conoscenza zero: nessun tracciamento dei download, nessun cookie invasivo e nessuna conservazione dei file.',
        'it': 'Informativa sulla Privacy — downsocial.net',
        'en': 'Detailed downsocial privacy policy: transient memory streaming, zero credential caching, strict SSL encryption, and complete GDPR compliance.',
        'es': 'Política de privacidad detallada: procesamiento transitorio en memoria, cero cookies de rastreo y cumplimiento estricto de privacidad.',
        'fr': 'Politique de confidentialité complète : traitement éphémère en mémoire, zéro trace personnelle et chiffrement SSL 256 bits.',
        'de': 'Vollständige Datenschutzerklärung: Keine Speicherung von Benutzerdaten, reine Stream-Verarbeitung im RAM und SSL-Verschlüsselung.',
        'hi': 'विस्तृत गोपनीयता नीति: मेमोरी में क्षणिक प्रोसेसिंग, कोई व्यक्तिगत डेटा लॉग नहीं और 100% सुरक्षित एसएसएल एन्क्रिप्शन।',
        'ar': 'سياسة خصوصية شاملة: معالجة فورية ومؤقتة في الذاكرة دون تخزين الوسائط، عدم جمع بيانات تعريف شخصية، وتشفير كامل عبر SSL.',
        'pt': 'Política de privacidade completa: streaming temporário na memória, sem cookies de rastreamento e segurança com criptografia SSL.',
        'bn': 'বিস্তারিত গোপনীয়তা নীতি: মেমরিতে তাৎক্ষণিক প্রসেসিং, কোনো ব্যক্তিগত তথ্য সংরক্ষণ না করা এবং উচ্চমানের SSL এনক্রিপশন সুরক্ষা।',
        'ru': 'Подробная политика конфиденциальности: потоковая обработка в оперативной памяти без сохранения файлов на сервере и шифрование SSL.',
        'id': 'Kebijakan privasi transparan: pemrosesan sementara di memori, tanpa pelacakan identitas pengguna, dan enkripsi SSL tingkat tinggi.',
        'zh': '详尽的隐私安全白皮书：严格执行全流程内存瞬时流转，绝不留存或转储任何视频媒体文件与用户个人隐私信息。',
        'ur': 'تفصیلی رازداری کی پالیسی: میموری میں عارضی پروسیسنگ، کوئی ذاتی ڈیٹا محفوظ نہیں اور مکمل محفوظ SSL انکرپشن۔'
    },
    'terms': {
        'it': "Consulta i termini e le condizioni d'uso della piattaforma gratuita di download video e audio downsocial.net.",
        'it': 'Termini di Servizio — downsocial.net',
        'en': 'downsocial Terms of Service: fair use offline archiving guidelines, intellectual property respect, and user responsibility disclaimers.',
        'es': 'Términos de servicio de downsocial: pautas de uso justo para archivo personal, respeto al derecho de autor y exención de responsabilidad.',
        'fr': 'Conditions d’utilisation de downsocial : règles d’archivage personnel équitable, respect du droit d’auteur et responsabilités des usagers.',
        'de': 'downsocial Nutzungsbedingungen: Richtlinien zur fairen persönlichen Archivierung, Urheberrechtskonformität und Haftungsausschluss.',
        'hi': 'downsocial सेवा की शर्तें: व्यक्तिगत ऑफलाइन देखने के दिशानिर्देश, बौद्धिक संपदा का सम्मान और कानूनी अस्वीकरण।',
        'ar': 'شروط خدمة downsocial: إرشادات الاستخدام الشخصي العادل للأرشفة غير التجارية، احترام حقوق الملكية الفكرية، وإخلاء المسؤولية القانونية.',
        'pt': 'Termos de serviço do downsocial: diretrizes de uso justo e pessoal, respeito aos direitos autorais e isenção de responsabilidade.',
        'bn': 'downsocial ব্যবহারের শর্তাবলী: ব্যক্তিগত অফলাইন সংরক্ষণের ফেয়ার ইউজ নির্দেশিকা, কপিরাইট সুরক্ষা ও আইনি দায়িত্বের বিবরণ।',
        'ru': 'Условия использования downsocial: правила добросовестного личного использования, защита авторских прав и правовые положения.',
        'id': 'Syarat layanan downsocial: panduan penggunaan wajar untuk arsip pribadi, perlindungan hak cipta, dan batasan tanggung jawab hukum.',
        'zh': '服务使用条款协议：严格规范个人合理使用边界，保护原创版权，明确第三方流媒体代理工具法律权责与合规免责声明。',
        'ur': 'downsocial سروس کی شرائط: منصفانہ ذاتی استعمال کے رہنما اصول، کاپی رائٹ کا احترام اور قانونی ذمہ داریوں کا بیان۔'
    }
}
