# scratch/enrich_all_seo_vocab.py
import json

ALL_VOCAB = {
    'fr': {
        'Quick Answer: How to Download Social Media Videos Free': 'Réponse Rapide : Comment Télécharger des Vidéos Gratuitement',
        'Quick Answer: How to Download Facebook Videos': 'Réponse Rapide : Comment Télécharger des Vidéos Facebook',
        'Quick Answer: How to Download Instagram Videos': 'Réponse Rapide : Comment Télécharger des Vidéos Instagram',
        'Quick Answer: How to Download TikTok Videos (No Watermark)': 'Réponse Rapide : Télécharger des Vidéos TikTok (Sans Filigrane)',
        'Quick Answer: How to Download YouTube Videos & Shorts': 'Réponse Rapide : Télécharger Vidéos & Shorts YouTube',
        'Quick Answer: How to Download Snapchat Spotlight Videos': 'Réponse Rapide : Télécharger Vidéos Spotlight Snapchat',
        'Quick Answer: How to Download Threads Videos': 'Réponse Rapide : Télécharger des Vidéos Threads',
        'Supported Platforms, Formats & Specifications': 'Plateformes, Formats et Spécifications Pris en Charge',
        'Why Choose downsocial over Competitors?': 'Pourquoi Choisir downsocial Face à la Concurrence ?',
        'Step-by-Step Device Download Guide': 'Guide de Téléchargement Étape par Étape',
        'Safe, Private & Anonymous Downloading': 'Téléchargement Sécurisé, Privé et Anonyme',
        'Platform': 'Plateforme',
        'Max Video Quality': 'Qualité Vidéo Max',
        'Audio Output': 'Sortie Audio',
        'Watermark Stripped?': 'Sans Filigrane ?',
        'Speed': 'Vitesse',
        'Other Downloaders': 'Autres Téléchargeurs',
        'Yes (100% Clean)': 'Oui (100% Propre)',
        'Instant (<2s)': 'Instantané (<2s)',
        'Up to 4K UHD': 'Jusqu’à 4K UHD',
        '320kbps MP3': 'MP3 320 kbps',
        'Clean & Ad-Free': 'Propre et Sans Pubs',
        'No Account Required': 'Aucun Compte Requis'
    },
    'de': {
        'Quick Answer: How to Download Social Media Videos Free': 'Kurzantwort: So laden Sie Social-Media-Videos kostenlos herunter',
        'Quick Answer: How to Download Facebook Videos': 'Kurzantwort: So laden Sie Facebook-Videos herunter',
        'Quick Answer: How to Download Instagram Videos': 'Kurzantwort: So laden Sie Instagram-Videos herunter',
        'Quick Answer: How to Download TikTok Videos (No Watermark)': 'Kurzantwort: So laden Sie TikTok-Videos ohne Wasserzeichen herunter',
        'Quick Answer: How to Download YouTube Videos & Shorts': 'Kurzantwort: So laden Sie YouTube-Videos und Shorts herunter',
        'Quick Answer: How to Download Snapchat Spotlight Videos': 'Kurzantwort: So laden Sie Snapchat-Spotlight-Videos herunter',
        'Quick Answer: How to Download Threads Videos': 'Kurzantwort: So laden Sie Threads-Videos herunter',
        'Supported Platforms, Formats & Specifications': 'Unterstützte Plattformen, Formate & Spezifikationen',
        'Why Choose downsocial over Competitors?': 'Warum downsocial gegenüber Konkurrenten wählen?',
        'Step-by-Step Device Download Guide': 'Schritt-für-Schritt-Anleitung für alle Geräte',
        'Safe, Private & Anonymous Downloading': 'Sicheres, privates und anonymes Herunterladen',
        'Platform': 'Plattform',
        'Max Video Quality': 'Maximale Videoqualität',
        'Audio Output': 'Audioausgabe',
        'Watermark Stripped?': 'Ohne Wasserzeichen?',
        'Speed': 'Geschwindigkeit',
        'Other Downloaders': 'Andere Downloader',
        'Yes (100% Clean)': 'Ja (100% sauber)',
        'Instant (<2s)': 'Sofort (<2s)',
        'Up to 4K UHD': 'Bis zu 4K UHD',
        '320kbps MP3': '320kbps MP3',
        'Clean & Ad-Free': 'Sauber und werbefrei',
        'No Account Required': 'Kein Konto erforderlich'
    },
    'hi': {
        'Quick Answer: How to Download Social Media Videos Free': 'त्वरित उत्तर: सोशल मीडिया वीडियो मुफ्त कैसे डाउनलोड करें',
        'Quick Answer: How to Download Facebook Videos': 'त्वरित उत्तर: फेसबुक वीडियो कैसे डाउनलोड करें',
        'Quick Answer: How to Download Instagram Videos': 'त्वरित उत्तर: इंस्टाग्राम वीडियो कैसे डाउनलोड करें',
        'Quick Answer: How to Download TikTok Videos (No Watermark)': 'त्वरित उत्तर: बिना वॉटरमार्क के टिकटॉक वीडियो कैसे डाउनलोड करें',
        'Quick Answer: How to Download YouTube Videos & Shorts': 'त्वरित उत्तर: यूट्यूब वीडियो और शॉर्ट्स कैसे डाउनलोड करें',
        'Quick Answer: How to Download Snapchat Spotlight Videos': 'त्वरित उत्तर: स्नैपचैट स्पॉटलाइट वीडियो कैसे डाउनलोड करें',
        'Quick Answer: How to Download Threads Videos': 'त्वरित उत्तर: थ्रेड्स वीडियो कैसे डाउनलोड करें',
        'Supported Platforms, Formats & Specifications': 'समर्थित प्लेटफ़ॉर्म, प्रारूप और विनिर्देश',
        'Why Choose downsocial over Competitors?': 'प्रतियोगियों के मुकाबले डाउनसोशल को क्यों चुनें?',
        'Step-by-Step Device Download Guide': 'डिवाइस अनुसार चरण-दर-चरण डाउनलोड गाइड',
        'Safe, Private & Anonymous Downloading': 'सुरक्षित, निजी और 100% अनाम डाउनलोडिंग',
        'Platform': 'प्लेटफ़ॉर्म',
        'Max Video Quality': 'अधिकतम वीडियो गुणवत्ता',
        'Audio Output': 'ऑडियो आउटपुट',
        'Watermark Stripped?': 'बिना वॉटरमार्क?',
        'Speed': 'गति',
        'Other Downloaders': 'अन्य डाउनलोडर',
        'Yes (100% Clean)': 'हाँ (100% स्वच्छ)',
        'Instant (<2s)': 'तुरंत (<2s)',
        'Up to 4K UHD': '4K UHD तक',
        '320kbps MP3': '320kbps MP3',
        'Clean & Ad-Free': 'स्वच्छ और विज्ञापन-मुक्त',
        'No Account Required': 'किसी खाते की आवश्यकता नहीं'
    },
    'ar': {
        'Quick Answer: How to Download Social Media Videos Free': 'إجابة سريعة: كيفية تنزيل فيديوهات التواصل الاجتماعي مجاناً',
        'Quick Answer: How to Download Facebook Videos': 'إجابة سريعة: كيفية تنزيل فيديوهات فيسبوك',
        'Quick Answer: How to Download Instagram Videos': 'إجابة سريعة: كيفية تنزيل مقاطع إنستغرام ريلز',
        'Quick Answer: How to Download TikTok Videos (No Watermark)': 'إجابة سريعة: كيفية تنزيل فيديوهات تيك توك بدون علامة مائية',
        'Quick Answer: How to Download YouTube Videos & Shorts': 'إجابة سريعة: كيفية تنزيل فيديوهات وشورتس يوتيوب',
        'Quick Answer: How to Download Snapchat Spotlight Videos': 'إجابة سريعة: كيفية تنزيل فيديوهات أضواء سناب شات',
        'Quick Answer: How to Download Threads Videos': 'إجابة سريعة: كيفية تنزيل فيديوهات ثريدز',
        'Supported Platforms, Formats & Specifications': 'المنصات والتنسيقات والمواصفات المدعومة',
        'Why Choose downsocial over Competitors?': 'لماذا تختار downsocial مقارنة بالمواقع الأخرى؟',
        'Step-by-Step Device Download Guide': 'دليل التنزيل خطوة بخطوة لجميع الأجهزة',
        'Safe, Private & Anonymous Downloading': 'تنزيل آمن وخاص ومجهول الهوية 100%',
        'Platform': 'المنصة',
        'Max Video Quality': 'أقصى دقة فيديو',
        'Audio Output': 'مخرج الصوت',
        'Watermark Stripped?': 'بدون علامة مائية؟',
        'Speed': 'السرعة',
        'Other Downloaders': 'المواقع الأخرى',
        'Yes (100% Clean)': 'نعم (100% نقي)',
        'Instant (<2s)': 'فوري (<2 ثانية)',
        'Up to 4K UHD': 'حتى 4K فائقة الوضوح',
        '320kbps MP3': 'صوت 320kbps MP3',
        'Clean & Ad-Free': 'نظيف وبدون إعلانات',
        'No Account Required': 'لا يتطلب حساباً'
    },
    'pt': {
        'Quick Answer: How to Download Social Media Videos Free': 'Resposta Rápida: Como Baixar Vídeos de Redes Sociais Grátis',
        'Quick Answer: How to Download Facebook Videos': 'Resposta Rápida: Como Baixar Vídeos do Facebook',
        'Quick Answer: How to Download Instagram Videos': 'Resposta Rápida: Como Baixar Vídeos do Instagram',
        'Quick Answer: How to Download TikTok Videos (No Watermark)': 'Resposta Rápida: Como Baixar Vídeos do TikTok (Sem Marca d’Água)',
        'Quick Answer: How to Download YouTube Videos & Shorts': 'Resposta Rápida: Como Baixar Vídeos e Shorts do YouTube',
        'Quick Answer: How to Download Snapchat Spotlight Videos': 'Resposta Rápida: Como Baixar Vídeos do Snapchat Spotlight',
        'Quick Answer: How to Download Threads Videos': 'Resposta Rápida: Como Baixar Vídeos do Threads',
        'Supported Platforms, Formats & Specifications': 'Plataformas, Formatos e Especificações Suportadas',
        'Why Choose downsocial over Competitors?': 'Por que escolher o downsocial em vez dos concorrentes?',
        'Step-by-Step Device Download Guide': 'Guia Passo a Passo para Todos os Dispositivos',
        'Safe, Private & Anonymous Downloading': 'Download Seguro, Privado e 100% Anônimo',
        'Platform': 'Plataforma',
        'Max Video Quality': 'Qualidade Máxima',
        'Audio Output': 'Saída de Áudio',
        'Watermark Stripped?': 'Sem Marca d’Água?',
        'Speed': 'Velocidade',
        'Other Downloaders': 'Outros Baixadores',
        'Yes (100% Clean)': 'Sim (100% Limpo)',
        'Instant (<2s)': 'Instantâneo (<2s)',
        'Up to 4K UHD': 'Até 4K UHD',
        '320kbps MP3': 'MP3 a 320kbps',
        'Clean & Ad-Free': 'Limpo e sem anúncios',
        'No Account Required': 'Nenhuma conta necessária'
    },
    'bn': {
        'Quick Answer: How to Download Social Media Videos Free': 'সহজ উত্তর: সোশ্যাল মিডিয়া ভিডিও ফ্রিতে কীভাবে ডাউনলোড করবেন',
        'Quick Answer: How to Download Facebook Videos': 'সহজ উত্তর: ফেসবুক ভিডিও কীভাবে ডাউনলোড করবেন',
        'Quick Answer: How to Download Instagram Videos': 'সহজ উত্তর: ইনস্টাগ্রাম রিলস কীভাবে ডাউনলোড করবেন',
        'Quick Answer: How to Download TikTok Videos (No Watermark)': 'সহজ উত্তর: ওয়াটারমার্ক ছাড়া টিকটক ভিডিও কীভাবে ডাউনলোড করবেন',
        'Quick Answer: How to Download YouTube Videos & Shorts': 'সহজ উত্তর: ইউটিউব ভিডিও এবং শর্টস কীভাবে ডাউনলোড করবেন',
        'Quick Answer: How to Download Snapchat Spotlight Videos': 'সহজ উত্তর: স্ন্যাপচ্যাট স্পটলাইট ভিডিও কীভাবে ডাউনলোড করবেন',
        'Quick Answer: How to Download Threads Videos': 'সহজ উত্তর: থ্রেডস ভিডিও কীভাবে ডাউনলোড করবেন',
        'Supported Platforms, Formats & Specifications': 'সমর্থিত প্ল্যাটফর্ম, ফরম্যাট এবং স্পেসিফিকেশন',
        'Why Choose downsocial over Competitors?': 'অন্যান্যদের চেয়ে ডাউনসোশ্যাল কেন বেছে নেবেন?',
        'Step-by-Step Device Download Guide': 'সকল ডিভাইসে ডাউনলোডের নির্দেশিকা',
        'Safe, Private & Anonymous Downloading': 'নিরাপদ, সম্পূর্ণ প্রাইভেট ও অজ্ঞাতনামা ডাউনলোড',
        'Platform': 'প্ল্যাটফর্ম',
        'Max Video Quality': 'সর্বোচ্চ কোয়ালিটি',
        'Audio Output': 'অডিও আউটপুট',
        'Watermark Stripped?': 'ওয়াটারমার্কহীন?',
        'Speed': 'গতি',
        'Other Downloaders': 'অন্যান্য ডাউনলোডার',
        'Yes (100% Clean)': 'হ্যাঁ (১০০% ক্লিন)',
        'Instant (<2s)': 'নিমেষেই (<২ সে.)',
        'Up to 4K UHD': '৪K UHD পর্যন্ত',
        '320kbps MP3': '৩২০kbps MP3',
        'Clean & Ad-Free': 'বিজ্ঞাপনমুক্ত ও নিরাপদ',
        'No Account Required': 'অ্যাকাউন্টের প্রয়োজন নেই'
    },
    'ru': {
        'Quick Answer: How to Download Social Media Videos Free': 'Краткий ответ: Как бесплатно скачать видео из соцсетей',
        'Quick Answer: How to Download Facebook Videos': 'Краткий ответ: Как скачать видео с Facebook',
        'Quick Answer: How to Download Instagram Videos': 'Краткий ответ: Как скачать рилс и видео с Instagram',
        'Quick Answer: How to Download TikTok Videos (No Watermark)': 'Краткий ответ: Как скачать видео с TikTok без водяного знака',
        'Quick Answer: How to Download YouTube Videos & Shorts': 'Краткий ответ: Как скачать видео и Shorts с YouTube',
        'Quick Answer: How to Download Snapchat Spotlight Videos': 'Краткий ответ: Как скачать видео из Snapchat Spotlight',
        'Quick Answer: How to Download Threads Videos': 'Краткий ответ: Как скачать видео из Threads',
        'Supported Platforms, Formats & Specifications': 'Поддерживаемые платформы, форматы и характеристики',
        'Why Choose downsocial over Competitors?': 'Почему выбирают downsocial, а не конкурентов?',
        'Step-by-Step Device Download Guide': 'Пошаговая инструкция для любых устройств',
        'Safe, Private & Anonymous Downloading': 'Безопасная, конфиденциальная и анонимная загрузка',
        'Platform': 'Платформа',
        'Max Video Quality': 'Максимальное качество',
        'Audio Output': 'Аудиовыход',
        'Watermark Stripped?': 'Без водяного знака?',
        'Speed': 'Скорость',
        'Other Downloaders': 'Другие загрузчики',
        'Yes (100% Clean)': 'Да (100% чисто)',
        'Instant (<2s)': 'Мгновенно (<2 с)',
        'Up to 4K UHD': 'До 4K UHD',
        '320kbps MP3': 'MP3 320 кбит/с',
        'Clean & Ad-Free': 'Чисто и без рекламы',
        'No Account Required': 'Аккаунт не требуется'
    },
    'id': {
        'Quick Answer: How to Download Social Media Videos Free': 'Jawaban Cepat: Cara Mengunduh Video Media Sosial Gratis',
        'Quick Answer: How to Download Facebook Videos': 'Jawaban Cepat: Cara Mengunduh Video Facebook',
        'Quick Answer: How to Download Instagram Videos': 'Jawaban Cepat: Cara Mengunduh Video Instagram Reels',
        'Quick Answer: How to Download TikTok Videos (No Watermark)': 'Jawaban Cepat: Cara Mengunduh Video TikTok (Tanpa Watermark)',
        'Quick Answer: How to Download YouTube Videos & Shorts': 'Jawaban Cepat: Cara Mengunduh Video & Shorts YouTube',
        'Quick Answer: How to Download Snapchat Spotlight Videos': 'Jawaban Cepat: Cara Mengunduh Video Snapchat Spotlight',
        'Quick Answer: How to Download Threads Videos': 'Jawaban Cepat: Cara Mengunduh Video Threads',
        'Supported Platforms, Formats & Specifications': 'Platform, Format & Spesifikasi yang Didukung',
        'Why Choose downsocial over Competitors?': 'Mengapa Memilih downsocial Dibandingkan Pesaing?',
        'Step-by-Step Device Download Guide': 'Panduan Unduh Langkah demi Langkah',
        'Safe, Private & Anonymous Downloading': 'Pengunduhan Aman, Privat & 100% Anonim',
        'Platform': 'Platform',
        'Max Video Quality': 'Kualitas Video Maks',
        'Audio Output': 'Keluaran Audio',
        'Watermark Stripped?': 'Bebas Watermark?',
        'Speed': 'Kecepatan',
        'Other Downloaders': 'Pengunduh Lain',
        'Yes (100% Clean)': 'Ya (100% Bersih)',
        'Instant (<2s)': 'Instan (<2 detik)',
        'Up to 4K UHD': 'Hingga 4K UHD',
        '320kbps MP3': 'MP3 320kbps',
        'Clean & Ad-Free': 'Bersih dan tanpa iklan',
        'No Account Required': 'Tanpa perlu akun'
    },
    'zh': {
        'Quick Answer: How to Download Social Media Videos Free': '快速解答：如何免费高速下载主流社交媒体音视频',
        'Quick Answer: How to Download Facebook Videos': '快速解答：如何高速下载 Facebook 视频',
        'Quick Answer: How to Download Instagram Videos': '快速解答：如何下载 Instagram Reels 与高清快拍',
        'Quick Answer: How to Download TikTok Videos (No Watermark)': '快速解答：如何下载 TikTok 无水印超清视频',
        'Quick Answer: How to Download YouTube Videos & Shorts': '快速解答：如何解析下载 YouTube 视频与 Shorts',
        'Quick Answer: How to Download Snapchat Spotlight Videos': '快速解答：如何下载 Snapchat Spotlight 竖版短视频',
        'Quick Answer: How to Download Threads Videos': '快速解答：如何提取下载 Meta Threads 讨论视频',
        'Supported Platforms, Formats & Specifications': '全平台媒体流解析支持规格与技术指标',
        'Why Choose downsocial over Competitors?': '为什么选择 downsocial 而非传统下载网站？',
        'Step-by-Step Device Download Guide': '全终端（手机/平板/电脑）分步下载指南',
        'Safe, Private & Anonymous Downloading': '安全、高密且完全匿名的无痕下载体验',
        'Platform': '社交平台',
        'Max Video Quality': '最高支持画质',
        'Audio Output': '音频分离规格',
        'Watermark Stripped?': '是否剔除水印？',
        'Speed': '解析流转时延',
        'Other Downloaders': '传统下载站点',
        'Yes (100% Clean)': '是（100% 纯净无水印）',
        'Instant (<2s)': '毫秒级响应（<2秒）',
        'Up to 4K UHD': '最高支持 4K 原画',
        '320kbps MP3': '320kbps 录音室 MP3',
        'Clean & Ad-Free': '纯净无弹窗广告',
        'No Account Required': '免登录、零个人信息搜集'
    }
}

from translate_seo_articles import VOCAB
VOCAB.update(ALL_VOCAB)

print("Updated VOCAB with all 12 languages!")
